---
output: 
  pdf_document:
    keep_tex: false
    fig_caption: yes
    latex_engine: pdflatex
    template: svm-latex-syllabus.tex
geometry: margin=1in

title: "POLI 0000: Course Title"
author: Prof. Frederick Solt
date: "Spring 2019"

email: "frederick-solt@uiowa.edu"
web: "cmcr-class.github.io"
officehours: "TTh  9:30 to 11:00 am and by appointment"
office: "324 Schaeffer Hall"
classroom: "103 Schaeffer Hall"
classhours: "T 11:00 am to 1:50 pm"
---

```{r include = FALSE}
library(tidyverse)
library(lubridate)

firstday <- "2019-01-15"
    
meetings <- ymd(firstday) + c(0:15) * weeks(1)

meeting_headers <- paste0("Week ", 1:16, ", ", months(meetings), " ", day(meetings))

```


# Overview

# Course Requirements

# Course Schedule

## `r meeting_headers[1]`: Introduction to the Course
*Assignment*: 

1. [Bryan, Jennifer. 2016. \textit{Happy Git and GitHub for the UseR.} Chapters 1-16.](http://happygitwithr.com)  Read this carefully and follow its instructions to get set up with \textsf{R}, RStudio, Git, and GitHub on your laptop before we meet.


## `r meeting_headers[2]`: The Replication Crisis and Reproducibility
*Readings*: 

1. [Aschwanden, Christie, and Maggie Koerth-Baker.  2016.  "How Two Grad Students Uncovered an Apparent Fraud---and a Way to Change Opinions on Transgender Rights." *FiveThirtyEight*, April 7 ](http://fivethirtyeight.com/features/how-two-grad-students-uncovered-michael-lacour-fraud-and-a-way-to-change-opinions-on-transgender-rights/), and [Dimitrova, Velichka.  2013.  "Reinhart-Rogoff Revisited: Coding Errors Happen---Key Problem Was in Not Making the Data Openly Available from the Start."  *LSE: The Impact Blog*, April 24.](http://blogs.lse.ac.uk/impactofsocialsciences/2013/04/24/reinhart-rogoff-revisited-why-we-need-open-data-in-economics/)
1. [Data Access and Research Transparency (DA-RT): A Joint Statement by Political Science Journal Editors.](http://journals.cambridge.org/action/displayAbstract?fromPage=online&aid=9911378&fulltextType=LT&fileId=S2049847015000448)
1. [*AJPS* Replication and Verification Policy](https://ajps.org/ajps-replication-policy/) and [*American Journal of Political Science* Guidelines for Preparing Replication Files.](https://ajpsblogging.files.wordpress.com/2015/03/ajps-guide-for-replic-materials-1-0.pdf)
1. [Gelman, Andrew, and Eric Loken.  2013.  "The Garden of Forking Paths: Why Multiple Comparisons Can Be a Problem, Even When There Is No 'Fishing Expedition' or '*p*-Hacking' and the Research Hypothesis Was Posited Ahead of Time."](http://www.stat.columbia.edu/~gelman/research/unpublished/p_hacking.pdf)
1. [Leek, Jeffrey T., and Roger D. Peng. 2015.  "Opinion: Reproducibile Research Can Still Be Wrong: Adopting a Prevention Approach." *Proceedings of the National Academy of Sciences* 112(6):1645-1646](http://www.pnas.org.proxy.lib.uiowa.edu/content/112/6/1645) and [Patil, Prasad, Roger D. Peng, and Jeffrey T. Leek.  2016.  "A Statistical Definition for Reproducibility and Replicability."  *bioRxiv*, July 29.](http://biorxiv.org/content/biorxiv/early/2016/07/29/066803.full.pdf)

## `r meeting_headers[3]`: 

## `r meeting_headers[4]`: 

## `r meeting_headers[5]`: 

## `r meeting_headers[6]`: 

## `r meeting_headers[7]`: 

## `r meeting_headers[8]`:

## `r meeting_headers[9]`: 

## `r meeting_headers[10]`: 

## `r meeting_headers[11]`:

## `r meeting_headers[12]`: 

## `r meeting_headers[13]`: 

## `r meeting_headers[14]`: 

## `r meeting_headers[15]`: 

## `r meeting_headers[16]`: 




